#!/usr/bin/env sh

GITPM_PATH="$HOME/.gitpm"
REPO_URL="https://github.com/si0ls/GitProfileManager"

case "$1" in

    uninstall)
        rm -r $GITPM_PATH
        ;;

    install)
        git clone $REPO_URL $GITPM_PATH
        git config --global init.templatedir $GITPM_PATH

        echo "Please use 'git init' in already existing repositories to use GitPM"
        ;;
    
    *)
        echo "Usage: $0 install|uninstall"
        ;;

esac
