#!/usr/bin/env bash
GITPM_PATH="$HOME/.gitpm"
GITPM_REPO="https://github.com/si0ls/GitProfileManager"

print_help() {
    echo -e "Usage: $0 <command>\n"
    echo -e "Default: install\n"
    echo -e "Commands:\n"
    echo -e "\tinstall\t\tInstall GitPM"
    echo -e "\thelp\t\tDisplay this help page"
    echo -e "\tuninstall\tUninstall GitPM\n"
}

uninstall() {
    rm -rf $GITPM_PATH
    sudo rm /usr/bin/git-pm
    echo -e "\nGitPM uninstalled\n"
}

install() {
    uninstall
    git clone $GITPM_REPO $GITPM_PATH
    sudo cp $GITPM_PATH/bin/git-pm /usr/bin
    sudo chmod 777 /usr/bin/git-pm
    chmod 777 $GITPM_PATH/hooks/pre-commit
    git config --global init.templatedir $GITPM_PATH
    echo -e "\nPlease use 'git init' in existing repositories to use GitPM"
    echo -e "Use 'git pm --help' to get GitPM command list\n"
}

case "$1" in
    help)
        print_help
        ;;

    install)
        install
        ;;

    uninstall)
        uninstall
        ;;

    *)
        install
        ;;

esac